<p><span style="font-size: 24pt; font-family: calibri;">Starting with Numpy</span></p>

In [1]:
#load the library and check its version
import numpy as np
np.__version__

'1.21.5'

<p><span style="font-size: 18pt; font-family: calibri;">Scalar basic operations</span></p>

In [2]:
a = 2; b = 5

print(f"a + b = {a+b}\n")

print(f"a - b = {a-b}\n")

print(f"a * b = {a*b}\n")

print(f"b/a = {b/a}\n")

print(f"mod(b,a) = {b%a}\n")

print(f"b^a = {b**a}\n")

print(f"sqrt(a) = {np.sqrt(a)}\n")

print(f"abs(-a) = {np.abs(-a)}\n")

print(f"floor(2.5) = {int(np.floor(2.5))}")





a + b = 7

a - b = -3

a * b = 10

b/a = 2.5

mod(b,a) = 1

b^a = 25

sqrt(a) = 1.4142135623730951

abs(-a) = 2

floor(2.5) = 2


<p><span style="font-size: 12pt;"><strong>Python List vs. Numpy array</strong></span></p>
<ul>
<li><strong><span style="font-size: 12pt;">Numpy Array</span>:</strong>&nbsp;<span style="font-size: 12pt;">a grid of indexed values, all of the same type. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.&nbsp;</span></li>
<li><span style="font-size: 12pt;"><strong>List:</strong> Python equivalent of an array, but is resizeable and can contain elements of different types.</span></li>
</ul>
<p style="margin-top: 12px; margin-bottom: 12px; overflow-wrap: break-word; font-size: 16px;">Numpy data structures perform better in:</p>
<ul style="padding: 0px; margin-right: 0px; margin-bottom: 6px; margin-left: 25px; font-size: 16px;">
<li><strong>Size</strong>&nbsp;- Numpy data structures&nbsp;take up less space</li>
<li><strong>Performance</strong>&nbsp;- they have a need for speed and are faster than lists</li>
<li><strong>Functionality</strong>&nbsp;- SciPy and NumPy have optimized functions such as linear algebra operations built in.</li>
</ul>

In [3]:
#create a list comprising numbers from 0 to 4
my_list = list(range(5))
print(f"List = {my_list}")
print(type(my_list))
print(type(my_list[0]))


List = [0, 1, 2, 3, 4]
<class 'list'>
<class 'int'>


In [4]:
#create array from list
my_array = np.array(my_list)
print(f"Array = {my_array}")
print(type(my_array))
print(type(my_array[0]))

Array = [0 1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [5]:
#Other array builders
my_array1 = np.array([0, 1, 2, 3, 4], dtype ='int')
print(f"Array 1 = {my_array1}")

my_array2 = np.array(range(5))
print(f"Array 2 = {my_array2}")

my_array3 = np.arange(0, 19, 3)
print(f"Array 3 = {my_array3}")

Array 1 = [0 1 2 3 4]
Array 2 = [0 1 2 3 4]
Array 3 = [ 0  3  6  9 12 15 18]


In [6]:
#Create a matrix (array of arrays)
my_matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(f"Matrix = {my_matrix}")
print(type(my_matrix))
print(type(my_matrix[0]))
print(type(my_matrix[0][0]))

Matrix = [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


<h3 style="color: #252c33; font-family: 'Open Sans', sans-serif; word-spacing: 1px;">Array Indexing and Data Accesing</h3>
<p style="color: #252c33; font-family: 'Open Sans', sans-serif; font-size: 14px; word-spacing: 1px;">The important thing to remember is that indexing in python starts at zero.</p>

In [7]:
#Access one element
Array = np.array(range(1, 10))
print(Array)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(Array[3]) #What value?

4


In [9]:
#get the last value
print(f"Last elememt of Array = {Array[-1]}")

#get the second last value
print(f"Second last elememt of Array = {Array[-2]}")


Last elememt of Array = 9
Second last elememt of Array = 8


In [10]:
#inicial:final(sin llegar):salto --> 1:4:1
print(Array)
print(f"elemments of Array = {Array[0:4:2]}")

[1 2 3 4 5 6 7 8 9]
elemments of Array = [1 3]


In [11]:
#from start to an index
print(f"First 4 elemments of Array = {Array[:4]}")

#from an index to end
print(f"From 5th index to end = {Array[4:]}")

#range among two indexes
print(f"From 5th index to 7th index = {Array[4:7]}")

First 4 elemments of Array = [1 2 3 4]
From 5th index to end = [5 6 7 8 9]
From 5th index to 7th index = [5 6 7]


In [12]:
#in a multidimensional array, access items by row and column index
Matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(Matrix[1][2]) #What value?

6


In [14]:
#Replace values --> Same as access
Array = np.array(range(1, 10))
Array[4] = 1000
print(f"Reemplazamos el indice 4 del array {np.array(range(1, 10))} --> {Array}\n")

Matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
Matrix[1][1] = 1000


print(f"Hacemos los mismo con la matriz:\n{Matrix}")

Reemplazamos el indice 4 del array [1 2 3 4 5 6 7 8 9] --> [   1    2    3    4 1000    6    7    8    9]

Hacemos los mismo con la matriz:
[[   1    2    3]
 [   4 1000    6]
 [   7    8    9]]


In [15]:
#dimensions of a vector/matrix
print(f"Array length = {len(Array)}") # --> valid for arrays and lists
print(f"Array dimensions = {Array.shape}")

print(f"\nMatrix length = {len(Matrix)}") # --> not valid for matrices!!
print(f"Matrix dimensions = {Matrix.shape}")

#know specific dimension
print(f"\nThe number of columns of Matrix is = {Matrix.shape[1]}")
ncols = Matrix.shape[1]

Array length = 9
Array dimensions = (9,)

Matrix length = 3
Matrix dimensions = (3, 3)

The number of columns of Matrix is = 3


<div style="line-height: 90%; margin-top: 10.0pt; margin-bottom: 0pt; margin-left: 0.25in; text-indent: -0.25in; text-align: left; direction: ltr; unicode-bidi: embed; word-break: normal;"><span style="font-size: 18pt;"><span style="font-family: calibri; color: black;">Basic Matrices and O</span><span style="font-family: calibri; color: black;">perations (I)</span></span></div>

In [16]:
#matrix of ones
Ones = np.ones((2,3), dtype=float)
print(f"Ones = \n{Ones}")

#matrix of zeros
Zeros = np.zeros((2,4), dtype=float)
print(f"\nZeros = \n{Zeros}")

Ones = 
[[1. 1. 1.]
 [1. 1. 1.]]

Zeros = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#transpose
Matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(f"Matrix =\n{Matrix}\n")

tp = np.transpose(Matrix)
print(f"Transpose =\n{tp}")

#idem
tp = Matrix.transpose()

Matrix =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose =
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
#reshape --> always read by rows
Matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(f"Matrix =\n{Matrix}\n")

rs = np.reshape(Matrix,(3,2))
print(f"Reshape(3,2) =\n{rs}")

#idem
rs = Matrix.reshape((3,2))

Matrix =
[[1 2 3]
 [4 5 6]]

Reshape(3,2) =
[[1 2]
 [3 4]
 [5 6]]


In [19]:
#Cloning arrays and matrices
Matrix = np.array([[1, 2, 3],[4, 5, 6]])
Matrix_b = Matrix
Matrix_copy = Matrix.copy()
print(Matrix_copy)

[[1 2 3]
 [4 5 6]]


<p><span style="font-size: 18pt;">Basic Matrix Operation (II)</span></p>

In [20]:
#Add elements of vector/matrix
Matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(f"Matrix =\n{Matrix}\n")

print(f"Add all elements = {Matrix.sum()}\n")

print(f"Add all elements by columns = {Matrix.sum(axis = 0)}\n")

print(f"Add all elements by rows = {Matrix.sum(axis = 1)}\n")

Matrix =
[[1 2 3]
 [4 5 6]]

Add all elements = 21

Add all elements by columns = [5 7 9]

Add all elements by rows = [ 6 15]



In [21]:
#find min and max of vector/matrix
Matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(f"Matrix =\n{Matrix}\n")

print(f"Minimum value of Matrix = {Matrix.min()}")
print(f"Position of Minimum value in Matrix = {Matrix.argmin()}\n")


print(f"Maximum value of Matrix = {Matrix.max()}")
print(f"Position of Maximum value in Matrix = {Matrix.argmax()}\n")

Matrix =
[[1 2 3]
 [4 5 6]]

Minimum value of Matrix = 1
Position of Minimum value in Matrix = 0

Maximum value of Matrix = 6
Position of Maximum value in Matrix = 5



<p><span style="font-size: 18pt;">Random numbers</span></p>

In [22]:
np.set_printoptions(precision=3) #print only 3 decimal positions

#random seed (not so random)
np.random.seed(333)

#random vector/matrix
rArray = np.random.rand(5)
print(f"random Array (length 5) = {rArray}\n")

rMatrix = np.random.rand(3,4)
print(f"random Matrix (3,4) = {rMatrix}") 

random Array (length 5) = [0.543 0.729 0.017 0.33  0.369]

random Matrix (3,4) = [[0.048 0.105 0.097 0.245]
 [0.873 0.052 0.06  0.239]
 [0.204 0.175 0.415 0.942]]
